application:
  host: 127.0.0.1
  port: 3000
database:
  host: 127.0.0.1
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email:
  base_url: localhost
  sender_email: zero2prod-test@zed.gay
  token: "very-secret-token"
  timeout_miliseconds: 10000
